### ISSUE TITLE
Request validation should be separated as a middleware to avoid Violating Single responsibility principle

### ISSUE THREAD

**Issue by pmnhatdn** [QuocAnhJ/node_mongo_boilerplate#3]
` const addBooks = async (req, res) => {
        try {
            /* Field validation */
            **req.checkBody('title', 'Title cannot be blank').notEmpty().trim();
            req.checkBody('author', 'Author cannot be blank').notEmpty().trim();
            req.checkBody('genre').trim();
            req.checkBody('read', 'Read is must boolean type').isBoolean().trim();**

`
Field Validation should be in a separated middleware.

router.post('/books', BookCreationValidatorMiddleware, addBooks);

**Comment by QuocAnhJ** [comment]
Fixed
